In [1]:
!pip install requests pandas openai

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.24.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
MONDAY_API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjYzMTAwNjk1MiwiYWFpIjoxMSwidWlkIjoxMDA4MTI1NzYsImlhZCI6IjIwMjYtMDMtMTBUMDU6NDk6NDIuMDAwWiIsInBlciI6Im1lOndyaXRlIiwiYWN0aWQiOjM0MTUzMjU3LCJyZ24iOiJhcHNlMiJ9.QQC8_dCEe7Sy3GNQ4uNVRIAN7280VRewJ38SHD0g_OA"

DEALS_BOARD_ID = "5027109094"
WORK_BOARD_ID = "5027109264"

In [11]:
import requests

url = "https://api.monday.com/v2"

headers = {
    "Authorization": MONDAY_API_KEY
}

def fetch_board(board_id):

    query = f"""
    {{
      boards(ids:{board_id}) {{
        name
        items_page(limit: 100) {{
          items {{
            name
            column_values {{
              column {{
                title
              }}
              text
            }}
          }}
        }}
      }}
    }}
    """

    response = requests.post(url, json={"query": query}, headers=headers)

    return response.json()

In [12]:
deals_data = fetch_board(DEALS_BOARD_ID)
work_data = fetch_board(WORK_BOARD_ID)

print("Deals board loaded")
print("Work orders board loaded")

Deals board loaded
Work orders board loaded

In [13]:
import pandas as pd

def convert_to_dataframe(api_response):

    items = api_response["data"]["boards"][0]["items_page"]["items"]

    rows = []

    for item in items:

        row = {"Item": item["name"]}

        for col in item["column_values"]:
            column_name = col["column"]["title"]
            row[column_name] = col["text"]

        rows.append(row)

    df = pd.DataFrame(rows)

    return df

In [14]:
deals_df = convert_to_dataframe(deals_data)
work_df = convert_to_dataframe(work_data)

deals_df.head()

,Item,Owner code,Client Code,Deal Status,Close Date (A),Closure Probability,Masked Deal value,Tentative Close Date,Deal Stage,Product deal,Sector/service,Created Date
0,Naruto,OWNER_001,COMPANY089,Open,,High,489360,2026-02-26,B. Sales Qualified Leads,Service + Spectra,Mining,2025-12-26
1,Sasuke,OWNER_001,COMPANY091,Open,,,17616960,2026-02-28,B. Sales Qualified Leads,None,Mining,2025-09-15
2,Sasuke,OWNER_002,COMPANY124,Open,,Medium,611700,2026-02-26,E. Proposal/Commercials Sent,None,Powerline,2025-11-12
3,Sakura,OWNER_002,COMPANY046,Open,,Low,2348928,2026-03-20,E. Proposal/Commercials Sent,None,Powerline,2025-10-14
4,Sakura,OWNER_002,COMPANY148,Open,,High,428190,2026-02-26,E. Proposal/Commercials Sent,None,Powerline,2025-10-10

In [15]:
work_df.head()

,Item,Customer Name Code,Serial #,Nature of Work,Last executed month of recurring project,Execution Status,Data Delivery Date,Date of PO/LOI,Document Type,Probable Start Date,...,Quantity billed (till date),Balance in quantity,Invoice Status,Expected Billing Month,Actual Billing Month,Actual Collection Month,WO Status (billed),Collection status,Collection Date,Billing Status
0,Scooby-Doo,WOCOMPANY_002,SDPLDEAL-075,One time Project,,Completed,2025-09-27,2025-10-29,Purchase Order,2025-05-31,...,,5360,,,,,,,,Update Required
1,Appa,WOCOMPANY_038,SDPLDEAL-101,Proof of Concept,,Not Started,,2025-07-31,Purchase Order,2025-08-11,...,,4,,,,,Open,,,
2,Sakura,WOCOMPANY_002,SDPLDEAL-002,Monthly Contract,Dec,Executed until current month,2025-12-31,2025-05-16,Purchase Order,2025-05-01,...,,3000,,,,,Open,,,Partially Billed
3,Sakura,WOCOMPANY_002,SDPLDEAL-003,One time Project,,Completed,,2025-05-08,Purchase Order,2025-05-20,...,,600,Not billed yet,,,,Open,,,
4,SpongeBob,WOCOMPANY_032,SDPLDEAL-004,One time Project,,Completed,,2025-05-06,LOA/LOI,2025-05-24,...,,59.33,,,,,Open,,,BIlled

In [16]:
deals_df = deals_df.fillna("Unknown")
work_df = work_df.fillna("Unknown")

In [17]:
deals_df["Masked Deal value"] = pd.to_numeric(
    deals_df["Masked Deal value"], errors="coerce"
)

In [18]:
total_pipeline = deals_df["Masked Deal value"].sum()

print("Total pipeline value:", total_pipeline)

Total pipeline value: 1042673427.0747999

In [19]:
deals_df.groupby("Sector/service")["Masked Deal value"].sum()

Sector/service
Construction                 1.223400e+05
DSP                          3.217542e+07
Mining                       3.266759e+08
Others                       6.361680e+06
Powerline                    4.134297e+07
Railways                     6.548119e+07
Renewables                   2.766107e+07
Sector/service               0.000000e+00
Security and Surveillance    7.340400e+06
Tender                       5.319646e+08
Unknown                      3.547860e+06
Name: Masked Deal value, dtype: float64

In [20]:
work_df["Execution Status"].value_counts()

Execution Status
Completed                       83
Executed until current month    12
Ongoing                          3
Not Started                      1
Pause / struck                   1
Name: count, dtype: int64

In [21]:
def answer_query(question):

    q = question.lower()

    if "pipeline" in q:
        total = deals_df["Masked Deal value"].sum()
        return f"Total pipeline value is {total}"

    if "sector" in q:
        sector_summary = deals_df.groupby("Sector/service")["Masked Deal value"].sum()
        return sector_summary

    if "work orders" in q:
        return work_df["Execution Status"].value_counts()

    return "Please ask about deals or work orders."

In [22]:
answer_query("How is our pipeline?")

'Total pipeline value is 1042673427.0747999'

In [28]:
def answer_query(question):

    q = question.lower()

    # pipeline by sector
    if "sector" in q:
        sector_summary = deals_df.groupby("Sector/service")["Masked Deal value"].sum()
        return sector_summary

    # total pipeline
    elif "total pipeline" in q or "pipeline value" in q:
        total = deals_df["Masked Deal value"].sum()
        return f"Total pipeline value is {total}"

    # general pipeline question
    elif "pipeline" in q:
        total = deals_df["Masked Deal value"].sum()
        deals = len(deals_df)
        return f"Pipeline contains {deals} deals with total value {total}"

    # work orders
    elif "work orders" in q:
        return work_df["Execution Status"].value_counts()

    else:
        return "Please ask about pipeline, sectors, or work orders."

In [29]:
answer_query("What is the total pipeline value?")

'Total pipeline value is 1042673427.0747999'

In [30]:
answer_query("Show pipeline by sector")

Sector/service
Construction                 1.223400e+05
DSP                          3.217542e+07
Mining                       3.266759e+08
Others                       6.361680e+06
Powerline                    4.134297e+07
Railways                     6.548119e+07
Renewables                   2.766107e+07
Sector/service               0.000000e+00
Security and Surveillance    7.340400e+06
Tender                       5.319646e+08
Unknown                      3.547860e+06
Name: Masked Deal value, dtype: float64

In [32]:
def answer_query(question):

    q = question.lower()

    # 1️⃣ Pipeline by sector
    if "sector" in q and "pipeline" in q:
        sector_summary = deals_df.groupby("Sector/service")["Masked Deal value"].sum()
        return sector_summary

    # 2️⃣ Highest sector
    elif "highest sector" in q or "top sector" in q:
        sector_summary = deals_df.groupby("Sector/service")["Masked Deal value"].sum()
        top_sector = sector_summary.idxmax()
        value = sector_summary.max()
        return f"The sector with highest pipeline value is {top_sector} with {value}"

    # 3️⃣ Total pipeline value
    elif "total pipeline" in q or "pipeline value" in q:
        total = deals_df["Masked Deal value"].sum()
        return f"Total pipeline value is {total}"

    # 4️⃣ General pipeline summary
    elif "pipeline" in q:
        total = deals_df["Masked Deal value"].sum()
        deals = len(deals_df)
        return f"Pipeline contains {deals} deals with total value {total}"

    # 5️⃣ Open deals
    elif "open deals" in q:
        open_deals = deals_df[deals_df["Deal Status"]=="Open"]
        return f"There are {len(open_deals)} open deals"

    # 6️⃣ Work orders summary
    elif "work orders summary" in q or "work orders" in q:
        return work_df["Execution Status"].value_counts()

    # 7️⃣ Active work orders
    elif "active work orders" in q:
        active = work_df[work_df["Execution Status"]=="Ongoing"]
        return f"There are {len(active)} active work orders"

    # 8️⃣ Completed projects
    elif "completed projects" in q or "completed work orders" in q:
        completed = work_df[work_df["Execution Status"]=="Completed"]
        return f"{len(completed)} projects are completed"

    # 9️⃣ Leadership update
    elif "leadership" in q or "summary" in q:
        total_pipeline = deals_df["Masked Deal value"].sum()
        active_projects = len(work_df[work_df["Execution Status"]=="Ongoing"])
        completed_projects = len(work_df[work_df["Execution Status"]=="Completed"])

        return f"""
Leadership Update

Total Pipeline Value: {total_pipeline}

Work Orders
Active: {active_projects}
Completed: {completed_projects}
"""

    # 🔟 Data quality check
    elif "missing" in q or "data quality" in q:
        missing = deals_df["Masked Deal value"].isna().sum()
        return f"{missing} deals have missing deal values."

    else:
        return "Sorry, I couldn't understand the question."

In [33]:
answer_query("How is our pipeline?")

'Pipeline contains 100 deals with total value 1042673427.0747999'

In [34]:
answer_query("What is the total pipeline value?")

'Total pipeline value is 1042673427.0747999'

In [35]:
answer_query("Show pipeline by sector")

Sector/service
Construction                 1.223400e+05
DSP                          3.217542e+07
Mining                       3.266759e+08
Others                       6.361680e+06
Powerline                    4.134297e+07
Railways                     6.548119e+07
Renewables                   2.766107e+07
Sector/service               0.000000e+00
Security and Surveillance    7.340400e+06
Tender                       5.319646e+08
Unknown                      3.547860e+06
Name: Masked Deal value, dtype: float64

In [36]:
answer_query("Which sector has highest pipeline?")

Sector/service
Construction                 1.223400e+05
DSP                          3.217542e+07
Mining                       3.266759e+08
Others                       6.361680e+06
Powerline                    4.134297e+07
Railways                     6.548119e+07
Renewables                   2.766107e+07
Sector/service               0.000000e+00
Security and Surveillance    7.340400e+06
Tender                       5.319646e+08
Unknown                      3.547860e+06
Name: Masked Deal value, dtype: float64

In [37]:
answer_query("How many open deals do we have?")

'There are 47 open deals'

In [38]:
answer_query("Show work orders summary")

Execution Status
Completed                       83
Executed until current month    12
Ongoing                          3
Not Started                      1
Pause / struck                   1
Name: count, dtype: int64

In [39]:
answer_query("How many active work orders?")

Execution Status
Completed                       83
Executed until current month    12
Ongoing                          3
Not Started                      1
Pause / struck                   1
Name: count, dtype: int64

In [40]:
def answer_query(question):

    q = question.lower()

    # -------------------------
    # PIPELINE / DEALS QUERIES
    # -------------------------

    if "pipeline by sector" in q or "show pipeline by sector" in q:
        sector_summary = deals_df.groupby("Sector/service")["Masked Deal value"].sum()
        return sector_summary

    elif "highest sector" in q or "top sector" in q:
        sector_summary = deals_df.groupby("Sector/service")["Masked Deal value"].sum()
        top_sector = sector_summary.idxmax()
        value = sector_summary.max()
        return f"The sector with the highest pipeline value is {top_sector} with {value}"

    elif "total pipeline" in q or "pipeline value" in q:
        total = deals_df["Masked Deal value"].sum()
        return f"Total pipeline value is {total}"

    elif "open deals" in q:
        open_deals = deals_df[deals_df["Deal Status"] == "Open"]
        return f"There are {len(open_deals)} open deals"

    elif "pipeline" in q:
        total = deals_df["Masked Deal value"].sum()
        deals = len(deals_df)
        return f"Pipeline currently has {deals} deals with total value {total}"

    # -------------------------
    # WORK ORDER QUERIES
    # -------------------------

    elif "active work orders" in q:
        active = work_df[work_df["Execution Status"] == "Ongoing"]
        return f"There are {len(active)} active work orders"

    elif "completed projects" in q or "completed work orders" in q:
        completed = work_df[work_df["Execution Status"] == "Completed"]
        return f"{len(completed)} projects are completed"

    elif "not started" in q:
        ns = work_df[work_df["Execution Status"] == "Not Started"]
        return f"{len(ns)} projects have not started yet"

    elif "work orders summary" in q:
        summary = work_df["Execution Status"].value_counts()
        return summary

    # -------------------------
    # LEADERSHIP SUMMARY
    # -------------------------

    elif "leadership" in q or "summary report" in q:

        total_pipeline = deals_df["Masked Deal value"].sum()

        active = len(work_df[work_df["Execution Status"] == "Ongoing"])
        completed = len(work_df[work_df["Execution Status"] == "Completed"])

        return f"""
Leadership Update

Total Pipeline Value: {total_pipeline}

Work Orders
Active: {active}
Completed: {completed}

Insight:
Current pipeline indicates strong deal flow with manageable operational workload.
"""

    # -------------------------
    # DATA QUALITY
    # -------------------------

    elif "missing" in q or "data quality" in q:

        missing = deals_df["Masked Deal value"].isna().sum()

        return f"{missing} deals have missing deal values."

    else:
        return "Sorry, I couldn't understand the question."

In [41]:
answer_query("How is our pipeline?")

'Pipeline currently has 100 deals with total value 1042673427.0747999'

In [42]:
answer_query("What is the total pipeline value?")

'Total pipeline value is 1042673427.0747999'

In [43]:
answer_query("Show pipeline by sector")

Sector/service
Construction                 1.223400e+05
DSP                          3.217542e+07
Mining                       3.266759e+08
Others                       6.361680e+06
Powerline                    4.134297e+07
Railways                     6.548119e+07
Renewables                   2.766107e+07
Sector/service               0.000000e+00
Security and Surveillance    7.340400e+06
Tender                       5.319646e+08
Unknown                      3.547860e+06
Name: Masked Deal value, dtype: float64

In [44]:
answer_query("Which sector has highest pipeline?")

'Pipeline currently has 100 deals with total value 1042673427.0747999'

In [45]:
answer_query("How many open deals?")

'There are 47 open deals'

In [46]:
answer_query("Show work orders summary")

Execution Status
Completed                       83
Executed until current month    12
Ongoing                          3
Not Started                      1
Pause / struck                   1
Name: count, dtype: int64

In [47]:
answer_query("How many active work orders?")

'There are 3 active work orders'

In [48]:
answer_query("How many completed projects?")

'83 projects are completed'

In [51]:
answer_query("Check missing deal values")

'36 deals have missing deal values.'

In [52]:
print(answer_query("Generate leadership update"))

Leadership Update

Total Pipeline Value: 1042673427.0747999

Work Orders
Active: 3
Completed: 83

Insight:
Current pipeline indicates strong deal flow with manageable operational workload.